### ISSUE TITLE
info.plist and .pch file prefix path issue.

### ISSUE THREAD

**Issue by hackiftekhar** [diegoreymendez/horizontalTableViewExample#1]
Info.plist and .pch file not found at compile time, because it's file path is incorrect.

Please replace
 '/Users/diegoreymendez/Documents/Diego/Personal/devalloc/Sample Code/HorizontalTableViewExample/Code/Horizontal TableView Example-Info.plist': 
by 'Code/Horizontal TableView Example-Info.plist' in your build setting->info.plist File

and replace
'/Users/diegoreymendez/Documents/Diego/Personal/devalloc/Sample Code/HorizontalTableViewExample/Code/Horizontal TableView Example-Prefix.pch'
by 'Code/Horizontal TableView Example-Prefix.pch' in your build setting->prefix Header

**Comment by diegoreymendez** [comment]
Fixed.  Thanks for the report.
